name: Deploy SahraTalk FrontEnd

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.1
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            # Stop and remove container if it exists
            if [ "$(docker ps -aq -f name=SahraTalkFE)" ]; then
                echo "Stopping and removing existing SahraTalkFE container..."
                docker stop SahraTalkFE
                docker rm SahraTalkFE
            else
                echo "No existing SahraTalkFE container found."
            fi

            # Remove image if it exists
            if [ "$(docker images -q omarsalhi1/sahratalk-fe:1.0)" ]; then
                echo "Removing existing image omarsalhi1/sahratalk-fe:1.0..."
                docker rmi omarsalhi1/sahratalk-fe:1.0
            else
                echo "No existing image omarsalhi1/sahratalk-fe:1.0 found."
            fi

            docker pull ${{ secrets.DOCKER_USERNAME }}/sahratalk-fe:1.0

            # Run the container 
            docker run -d --name SahraTalkFE -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/sahratalk-fe:1.0

            # Verify the container is running
            docker ps -a | grep SahraTalkFE
            echo "Deployment completed!"